# Introducción a Python - Funciones y módulos

Con todo lo visto en los anteriores notebooks deberíamos ser capaces de crear cualquier programa. En este apartado vamos a ver cómo se puede (y debe) estrucurar el código de los programas Python de forma que se asegure su reusabilidad y se minimice los posibles puntos de error de los mismos.

### Funciones

<ul>
<li>Puede entenderse como un nombre asignado a un bloque de código que permite su posterior invocación.</li>
<li>Dispone de un conjunto de parámetros de entrada (opcionales) sobre los que trabajará el bloque de código interno.</li>
<li>Ofrecen un resultado de salida (opcional) que podrá ser utilizado por el código que invocó a la función.</li>
<li>Permiten encapsular código de forma que pueda ser reutilizado en varios puntos de un programa.</li>
<li>Evitan la necesidad de copiar y pegar código.</li>
<li>Facilita el mantenimiento y reduce los posibles puntos de error.</li>
<li>Permiten "generalizar" código al trabajar sobre unos parámetros de entrada que pueden ser "variables".</li>
</ul>

In [1]:
list_1 = ["uno", "dos", "tres", "cuatro", "cinco", "treinta"]
list_C = []
for element in list_1:
    if element[0] == "c":
        list_C.append(element.upper())
print (list_C)

['CUATRO', 'CINCO']


¿Qué pasa si quisiésemos usar una lista distina? ¿Qué pasa si queremos seleccionar sólo los elementos que empiezan por "t"? ¿Qué pasa si queremos devolver los elementos en minúscula? Tendríamos que replicar varias veces el mismo código. Aquí es donde las funciones muestran su potencial.

In [2]:
def mi_funcion(lista, inicial, a_mayuscula):
    list_out = []
    for element in lista:
        if element[0] == inicial:
            if a_mayuscula:
                list_out.append(element.upper())
            else:
                list_out.append(element.lower())
    return list_out

In [3]:
list_1 = ["uno", "dos", "tres", "cuatro", "cinco", "treinta"]
print (mi_funcion(list_1, "c", True))
print (mi_funcion(list_1, "u", False))
print (mi_funcion(list_1, "t", True))

['CUATRO', 'CINCO']
['uno']
['TRES', 'TREINTA']


#### Variables internas y globales

Hay que señalizar que las variables que se van usando a lo largo de la función sólo existen dentro de la función, de manera que si queremos tener acceso a alguna de estas variables internas, en principio no se podría

In [4]:
print(element)

treinta


Para poder extraer alguna variable, hay que retocar el código y declarar aquellas variables que sean **globales**. Una vez hagamos esto y ejecutemos la función (al menos) 1 vez, ya tendremos disponible esta variable

In [5]:
def mi_funcion(lista, inicial, a_mayuscula=True):
    global list_out
    list_out = []
    for element in lista:
        if element[0] == inicial:
            if a_mayuscula:
                list_out.append(element.upper())
            else:
                list_out.append(element.lower())
    return list_out

In [6]:
mi_funcion(list_1,'c')

['CUATRO', 'CINCO']

In [7]:
print(element)

treinta


#### Argumentos opcionales

Podemos asignar valores por defecto a los parámetros de la función.

In [8]:
def mi_funcion(lista, inicial, a_mayuscula=True):
    list_out = []
    for element in lista:
        if element[0] == inicial:
            if a_mayuscula:
                list_out.append(element.upper())
            else:
                list_out.append(element.lower())
    return list_out

list_1 = ["uno", "dos", "tres", "cuatro", "cinco", "treinta"]
print (mi_funcion(list_1, "c"))
print (mi_funcion(list_1, "u", False))
print (mi_funcion(list_1, "t", True))

['CUATRO', 'CINCO']
['uno']
['TRES', 'TREINTA']


#### Especificar el nombre de los argumentos en la llamada

Se puede especificar el nombre de los argumentos de entrada en la llamada, eliminando la necesidad de mantener su orden (funcionamiento por defecto si no se especifica nombre).

In [9]:
list_1 = ["uno", "dos", "tres", "cuatro", "cinco", "treinta"]
print (mi_funcion(inicial="c", lista=list_1))
print (mi_funcion(a_mayuscula = True, inicial="c", lista=list_1))

['CUATRO', 'CINCO']
['CUATRO', 'CINCO']


#### Retorno de múltiples elementos

Aunque, en general, el retorno de las funciones será único (un único valor que se podrá asignar a una variable en el código que invoca), sería posible devolver una secuencia y recoger los resultados en diferentes variables (por las propiedades vistas en la presentación de secuencias).

In [10]:
def mi_funcion(lista, inicial, a_mayuscula=True):
    list_out = []
    for element in lista:
        if element[0] == inicial:
            if a_mayuscula:
                list_out.append(element.upper())
            else:
                list_out.append(element.lower())
    return (len(list_out), list_out)

In [11]:
long_lista, la_lista = mi_funcion(list_1,"c")

In [12]:
print(long_lista)
print(la_lista)

2
['CUATRO', 'CINCO']


### Módulos / Paquetes

<ul>
    <li>Por defecto, en un script de Python tienes acceso a todas las variables y funciones definidas en el propio fichero.</li>
    <li>Es posible acceder a elementos definidos en otros ficheros mediante la importación de módulos.</li>
    <li>Un fichero .py es un módulo en Python cuyo nombre es el mismo que el del fichero (sin extensión).</li>
    <li>La forma de incorporar elementos definidos en un módulo es mediante el uso de la sentencia <i>import</i>.</li>
</ul>

#### Importar el módulo completo

Se importa todo el contenido del módulo y es necesario utilizar el alias de módulo delante de las funciones.

In [13]:
import numpy
array = numpy.array([[1, 2], [3, 4]])
mean = numpy.mean(array)
print (array)
print (mean)

[[1 2]
 [3 4]]
2.5


#### Conocer los atributos del módulo. `dir`

Podemos tener acceso a las clases y funciones del módulo con la función `dir`.\
**Ojo**: No podemos directamente acceder a los atributos de estas subclases, para ello, hay que hacerlo específicamente.

In [14]:
import numpy
dir(numpy)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distribut

#### Importar todo el contenido del módulo

Se importa todo el contenido del módulo y se incorporan sus funciones al entorno de trabajo actual, por lo que no es necesario especificar un alias. CUIDADO: esto sobreescribiría cualquier función de mismo nombre del entorno de trabajo.

In [15]:
from numpy import *
array = array([[1, 2], [3, 4]])
media = mean(array)
print (array)
print (media)

[[1 2]
 [3 4]]
2.5


#### Importar un elemento específico el módulo

Se importa únicamente el elemento seleccionado, aunque también hay peligro de sobreescritura.

In [16]:
from numpy import array
array = array([[1, 2], [3, 4]])
media2 = mean(array)
print (array)
print(media2)

[[1 2]
 [3 4]]
2.5


#### Importar con alias

Se puede especifcar un alias a los elementos importados de forma que asegures que no hay sobreescritura.

In [17]:
from numpy import array as array_de_numpy
array = array_de_numpy([[1, 2], [3, 4]])
print (array)

[[1 2]
 [3 4]]


### Instalación de módulos

Al contrario que en R, en Python no se dispone de una función para instalar módulos directamente desde el intérprete y se debe hacer desde la consola. La herramienta básica para la gestión de paquetes es *pip*.

#### Herramienta: pip

pip instala paquetes disponibles en el repositorio PyPI (índice de paquetes de Python). Los comandos más comunes son:<br/>
<ul>
<li>list: Listado de paquetes actualmente instalados en el entorno.</li>
<li>search &lt;search_string&gt;: Búsqueda de paquetes en el repositorio.</li>
<li>install &lt;package&gt;: Instalación de paquetes no disponibles.</li>
<li>update &lt;package&gt;: Actualización del paquete a la última versión disponible.</li>
</ul>