# La base de NumPy - ndarray

Toda la libería de NumPy se articula alrededor de una única estructura de datos: la matriz multidimensional o ndarray (N-dimensional array).<br/>

### Características básicas de ndarray

<ul>
<li>Un ndarray puede contener elementos de <b>CUALQUIER TIPO</b></li>
<li>Todos los elementos de un ndarray deben tener <b>EL MISMO TIPO</b>.</li>
<li>El tamaño de un ndarray (número de elementos) se define en el momento de la creación y no puede modificarse.</li>
<li>Pero la organización de esos elementos entre diferentes dimensiones sí puede modificarse</li>
</ul>

### Uso básico de cualquier elemento de NumPy

Hay que recordar que NumPy no es un módulo del core de Python por lo que SIEMPRE habrá que importarlo de forma completa o componente a componente.

In [1]:
import numpy as np

### Creación básica de ndarrays

Existen varias formas de crear un ndarray en NumPy. Vamos a ver las más relevantes.

#### Creación de un ndarray cuyos elementos son una secuencia numérica

In [2]:
# Un parámetro: desde 0 (incluido) hasta el valor indicado (no incluido)
array_secuencia_1 = np.arange(10)
array_secuencia_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Dos parámetros: desde el primer valor (incluido) hasta el segundo valor (no incluido)
array_secuencia_2 = np.arange(5, 10)
array_secuencia_2

array([5, 6, 7, 8, 9])

In [4]:
# Tres parámetros: desde el primer valor (incluido) hasta el segundo (no incluido) con saltos del tercer valor
array_secuencia_3 = np.arange(5, 20, 2)
array_secuencia_3

array([ 5,  7,  9, 11, 13, 15, 17, 19])

#### Creación de un ndarray a partir de una secuencia básica de Python

In [5]:
# Unidimensional
array_basico = np.array([1, 2, 3, 4, 5])
type(array_basico)

numpy.ndarray

In [6]:
# Multidimensional
array_basico_multidimensional = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
array_basico_multidimensional

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Consulta de la composición de un ndarray

<ul>
<li><b>dtype</b>: Tipo del contenido del ndarray.</li>
<li><b>ndim</b>: Número de dimensiones/ejes del ndarray.</li>
<li><b>shape</b>: Estructura/forma del ndarray, es decir, número de elementos en cada uno de los ejes/dimensiones.</li>
<li><b>size</b>: Número total de elementos en el ndarray.</li>
</ul>

In [7]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
# Tipo de dato (único)
array.dtype

dtype('int64')

In [9]:
# Número de dimensiones
array.ndim

2

In [10]:
# Forma/Dimensiones
array.shape

(3, 4)

In [11]:
# Número total de elementos
array.size

12

### Operaciones aritméticas entre ndarrays y escalares

In [12]:
array = np.array([1, 2, 3, 4, 5, 6], dtype=np.float64)
array

array([1., 2., 3., 4., 5., 6.])

In [13]:
# Suma
array + 5

array([ 6.,  7.,  8.,  9., 10., 11.])

In [14]:
# Resta
array - 2

array([-1.,  0.,  1.,  2.,  3.,  4.])

In [15]:
# Multiplicación
array * 3

array([ 3.,  6.,  9., 12., 15., 18.])

In [16]:
# División
1 / array

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667])

In [17]:
# División entera
array // 2

array([0., 1., 1., 2., 2., 3.])

In [18]:
# Potencia
array ** 2

array([ 1.,  4.,  9., 16., 25., 36.])

In [19]:
# Asignación con operador
print(array)
array += 1
print(array)

[1. 2. 3. 4. 5. 6.]
[2. 3. 4. 5. 6. 7.]


### Operaciones aritméticas entre ndarrays

<b>IMPORTANTE:</b> Los dos términos de la operación tienen que ser ndarrays de las mismas dimensiones y forma. Se aplica la operación elemento a elemento.

In [20]:
array = np.array([1, 2, 3, 4, 5, 6], dtype=np.float64)
array2 = np.array([10, 20, 30, 40, 50, 60], dtype=np.float64)

In [21]:
print(array)
print(array2)

[1. 2. 3. 4. 5. 6.]
[10. 20. 30. 40. 50. 60.]


In [22]:
# Suma (elemento a elmento)
array + array2

array([11., 22., 33., 44., 55., 66.])

In [23]:
# Resta (elemento a elmento)
array - array2

array([ -9., -18., -27., -36., -45., -54.])

In [24]:
# Multiplicación (elemento a elmento)
array * array2

array([ 10.,  40.,  90., 160., 250., 360.])

In [25]:
# División (elemento a elmento)
array / array2

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [26]:
# Asignación con operador
array += array2
array

array([11., 22., 33., 44., 55., 66.])

### Indexación y slicing básico

En ndarrays unidimensionales el funcionamiento es idéntico al que se tiene en secuencias básicas de Python. Es decir, se utiliza la indexación [a:b:c].

In [27]:
array = np.arange(1, 11)

In [28]:
# Indexación con primer parámetro
array[2]

3

In [29]:
# Indexación con primer y segundo parámetro
array[2:5]

array([3, 4, 5])

In [30]:
# Indexación con tercer parámetro
array[::2]

array([1, 3, 5, 7, 9])

In [31]:
# Indexación con negativos
array[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

En ndarrays multidimensionales, existen dos posibles formas de realizar el acceso:<br/>
<ul>
<li><b>Mediante indexación recursiva:</b> array[a:b:c en dim_1][a:b:c en dim_2]...[a:b:c en dim_n]</li>
<li><b>Mediante indexación con comas:</b> array[a:b:c en dim_1, a:b:c en dim_2, ...a:b:c en dim_n]</li>
</ul>

In [32]:
array = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]])
array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [33]:
# Forma de la matriz
array.shape

(2, 2, 4)

In [34]:
# Indexación recursiva primer nivel
array[1]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [35]:
# Indexación recursiva segundo nivel
array[1][0]

array([ 9, 10, 11, 12])

In [36]:
# Indexación recursiva tercer nivel
array[1][0][3]

12

In [37]:
# Indexación con comas segundo nivel
array[1, 0]

array([ 9, 10, 11, 12])

In [38]:
# Indexación con comas tercer nivel
array[1, 0, 3]

12

In [39]:
# Indexación recursiva tercer nivel con slice
array[0][0][:2]

array([1, 2])

In [40]:
# Indexación recursiva tercer nivel con slice de índice negativo
array[1][0][::-1]

array([12, 11, 10,  9])

Del mismo modo a como ocurre en Python básico, se puede utilizar la indexación/slicing para modificar secciones del contenido de un ndarray.

In [41]:
array = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])

In [42]:
# Modificación de una posición
array[0][1] = 50
array

array([[ 1, 50,  3,  4],
       [ 5,  6,  7,  8]])

In [43]:
# Modificación de un slice
array[0][::2] = 30
array

array([[30, 50, 30,  4],
       [ 5,  6,  7,  8]])

### Indexación y slicing booleano

In [44]:
personas = np.array(['Miguel', 'Pedro', 'Juan', 'Miguel'])
personas

array(['Miguel', 'Pedro', 'Juan', 'Miguel'], dtype='<U6')

In [45]:
datos = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[-5, -6, -7, -8],[-1, -2, -3, -4]])
datos

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [-5, -6, -7, -8],
       [-1, -2, -3, -4]])

In [46]:
# Indexación/slicing booleano sobre valores
datos[datos < 0]

array([-5, -6, -7, -8, -1, -2, -3, -4])

In [47]:
# Máscara booleana
personas == 'Miguel'

array([ True, False, False,  True])

In [48]:
# Indexación/slicing mediante máscara
datos[personas == 'Miguel']

array([[ 1,  2,  3,  4],
       [-1, -2, -3, -4]])

In [49]:
# Indexación/slicing mediante máscara y básico combinado
datos[personas == 'Miguel', :3]

array([[ 1,  2,  3],
       [-1, -2, -3]])

In [50]:
# Indexación/slicing mediante máscara negativo por operador
datos[personas != 'Miguel']

array([[ 5,  6,  7,  8],
       [-5, -6, -7, -8]])

In [51]:
# Indexación/slicing mediante máscara negativa por signo
datos[~(personas == 'Miguel')]

array([[ 5,  6,  7,  8],
       [-5, -6, -7, -8]])

De nuevo, podemos utilizar indexación/slicing booleano para realizar modificaciones sobre el contenido de un ndarray.

In [52]:
# Eliminación de valores negativos mediante slicing
print("Antes:")
print(datos)
print("\n")
print("Elementos que vamos a poner a 0:")
print(datos[datos < 0])
array[datos < 0] = 0
print("\n")
print("Despues:")
print(array)

Antes:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [-5 -6 -7 -8]
 [-1 -2 -3 -4]]


Elementos que vamos a poner a 0:
[-5 -6 -7 -8 -1 -2 -3 -4]


IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 4

### Indexación y slicing basado en secuencias de enteros - Fancy indexing

In [53]:
array = np.empty((8, 4))
for i in range(8):
    array[i] = i
array

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [54]:
# Indexación/slicing de un conjunto (arbitrario) de elementos
array[[2, 5]]

array([[2., 2., 2., 2.],
       [5., 5., 5., 5.]])

In [55]:
# Indexación/slicing de un conjunto (arbitrario) de elementos (índices negativos)
array[[-2, -5]]

array([[6., 6., 6., 6.],
       [3., 3., 3., 3.]])

También podemos indexar de manera arbitraria en múltiples dimensiones, utilizando para ello, una secuencia de enteros por cada dimensión. El resultado será la combinación de secuencias.

In [56]:
array = np.arange(32).reshape((8, 4))
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [57]:
# Indexación/slicing con una secuencia de varios niveles (elemento a elemento)
array[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [58]:
# Indexación/slicing con una secuencia de varios niveles (región resultante)
array[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### Trasposición y modificación de ejes/dimensiones

In [59]:
array = np.arange(15)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [60]:
# Modificación de ejes/dimensiones
array2 = array.reshape(3, 5)
array2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [61]:
# Trasposición de ejes/dimensiones"
array2.T


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

**Axis**

Valor 0: Aplicará la función por filas


Valor 1: Aplicará la función por columnas

In [62]:
array2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [63]:
array2.sum()

105

In [66]:
array2.sum(axis = 1)

array([10, 35, 60])

In [65]:
array2.sum(axis = 0)

array([15, 18, 21, 24, 27])