# Álgebra lineal

Hasta el momento hemos visto cómo aplicar funciones "elemento a elemento" a matrices multidimensionales pero, en ningún caso, hemos aplicado funciones de cálculo matricial sobre las mismas. NumPy ofrece un amplio conjunto de funciones que permiten realizar multitud de tratamientos/operaciones matriciales. Todas estas funciones están disponibles a través del submódulo <b>linalg</b>.

In [1]:
import numpy as np
import numpy.linalg as linalg

Algunas de las más comunes son:<br/>
<ul>
<li><b>diag:</b> Recupera la diagonal principal del ndarray pasado como parámetro.</li>
<li><b>dot:</b> Realiza el producto escalar de dos ndarray.</li>
<li><b>trace:</b> Calcula la suma de los elementos de la diagonal principal.</li>
<li><b>det:</b> Calcula el determinante de un ndarray.</li>
<li><b>eig:</b> Calcula los autovalores y autovectores de un ndarray.</li>
<li><b>inv:</b> Calcula la inversa de una matriz.</li>
<li><b>qr:</b> Calcula la descomposición QR de una matriz.</li>
<li><b>svd:</b> Calcula la descomposición de valores singulares (Singular Value Decomposition) de una matriz.</li>
<li><b>solve:</b> Calcula el resultado del sistema lineal Ax = B donde A y B son las matrices de entrada y x la salida.</li>
<li><b>lstsq:</b> Calcula la solución de mínimos cuadrados a y = Xb, donde y y b son los parámetros de entrada y X la salida.</li>
</ul>

In [2]:
array1 = np.random.randn(3, 3)
array1

array([[ 1.45984894, -0.99510754,  1.71450986],
       [ 0.01979765, -0.97796586,  0.42703974],
       [-0.58123901, -0.8488042 ,  0.36825343]])

In [3]:
np.diag(array1)

array([ 1.45984894, -0.97796586,  0.36825343])

In [4]:
array = np.arange(9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.dot(array, array)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [6]:
linalg.inv(array1)

array([[-0.00312959,  1.46008101, -1.678591  ],
       [ 0.34261929, -2.05721516,  0.79045692],
       [ 0.78477926, -2.43722602,  1.88804918]])

In [7]:
linalg.solve(array1,array)

array([[-5.691303  , -5.91294259, -6.13458218],
       [-1.42890396, -2.35304291, -3.27718186],
       [ 4.01661705,  4.25221948,  4.4878219 ]])

In [8]:
q,r = linalg.qr(array)
print("q:")
print(q)
print("r:")
print(r)

q:
[[ 0.          0.91287093  0.40824829]
 [-0.4472136   0.36514837 -0.81649658]
 [-0.89442719 -0.18257419  0.40824829]]
r:
[[-6.70820393e+00 -8.04984472e+00 -9.39148551e+00]
 [ 0.00000000e+00  1.09544512e+00  2.19089023e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16]]
